spree_theme/config/routes.rb
Spree::Core::Engine.add_routes do

  root :to => 'template_themes#page'
  # Add your extension routes here
  resources :template_themes do
     member do
       get :preview # add function preview_template_theme_path
       post :get_param_values # to support post data>1024byte
       post :update_param_value
       post :update_layout_tree
       get  :upload_file_dialog
       post :upload_file_dialog
     end
     collection do
       #get :preview # add function preview_template_themes_path
     end
     resources :page_layouts, only: [:edit,:update] do
     end
  end

  namespace :api, :defaults => { :format => 'json' } do
    namespace :v1 do
      resource :wechat, only: [:show, :create]
      
      post 'auth/sign_in', :to => 'auth#sign_in'
      #post 'auth/facebook', :to => 'auth#facebook'
      #post 'auth/sign_up', :to => 'auth#sign_up'
    end
  end

  ##############################################################################
  # mulit site
  # one click get form to trial
  get 'one_click_trial' => 'sites#one_click_trial', :as => :one_click_trial
  # bottom signup form
  post 'quick_lunch',:to => 'sites#quick_lunch', :as => :quick_lunch
  # create site with template_theme
  get 'new_site' => 'sites#new', :as => :new_site
  post 'create_site' => 'sites#create', :as => :create_site
  resources :sites, :only => [:show]
  ##############################################################################

  namespace :admin do
    resources :sites
    resources :comments
    resources :comment_types
    resources :orders do
      member do
        get :comments
      end
      resources :shipments do
        member do
         get :comments
       end
      end
    end
    resources :relation_types
    resources :products, only: [] do
      get :related, on: :member
      resources :relations do
        collection do
          post :update_positions
        end
      end
    end

  end

  namespace :admin do
      resources :posts do
        resources :files,   :controller => "post_files" do
          collection do
            post :update_positions
          end
        end
        resources :products, :controller => "post_products"
        resources :categories, :controller => "post_categories"
      end
  end

  resources :comments, :only=>[:create] do
    collection do
      get :new_to_site
    end
  end

  get '(/:c(/:r))' => 'template_themes#page' , :c => /\d[^\/]*/ # :c, taxon_id-friendly_id,  :r, product_id-friendly_id
  get '/post/:c/:p' => 'template_themes#page', :c => /\d[^\/]*/ #
  get '/preview/:id' => 'template_themes#preview' #preview template_theme, for design shop only.

  get '/under_construction', :to => 'template_themes#under_construction', :as => :under_construction
  post '/create_admin_session', :to => 'template_themes#create_admin_session', :as => :create_admin_session
  get '/new_admin_session', :to => 'template_themes#new_admin_session', :as => :new_admin_session
  post '/check_email', :to => 'users#check_email', :as => :check_email


  #api extension
  namespace :api, :defaults => { :format => 'json' } do
    namespace :v1 do
      resources :products, only: [] do
        get :related, on: :member
        resources :relations do
          collection do
            post :update_positions
          end
        end
      end

      resources :template_themes do
        member do
          get :jstree
        end
        resources :page_layouts do
          member do
            get :jstree
          end
        end
      end
      resources :taxons, :only => [:index] do
        collection do
         get :global
       end
      end
    end
  end

  namespace :admin do
    resources :template_texts
    resources :template_files
    resources :template_themes do
      collection do
        get :native
        get :foreign
      end
      member do
        get :config_resource   # assign resource(menu, image)
        get :config_context    #
        get :config_data_source#
        #get :prepare_import    # assign resource(menu, image)
        post :copy
        post :release
        patch :apply
      end

      resources :page_layouts do
        member do
          get :config_resource
          get :config_context
          get :config_data_source
          post :update_resource
          post :update_context
          post :update_data_source
        end
      end
    end
  end
end

spree_theme/app/controllers/spree/admin/comment_types_controller.rb
class Spree::Admin::CommentTypesController < Spree::Admin::ResourceController
end

spree_theme/app/views/spree/admin/comment_types/_form.html.erb
<div id="admin_comment_type_form_fields" data-hook>
  <%= f.field_container :name do %>
    <%= f.label :name, Spree.t(:name) %><br />
    <%= f.text_field :name, :class => 'fullwidth title' %>
    <%= error_message_on :comment_type, :name %>
  <% end %>

  <%= f.field_container :applies_to do %>
    <%= f.label :applies_to, Spree.t(:applies_to) %><br />
    <%= f.text_field :applies_to, :value => f.object.nil? ? 'Order' : f.object.applies_to, :class => 'fullwidth title' %>
    <%= error_message_on :comment_type, :applies_to%>
  <% end %>

</div>

spree_theme/app/views/spree/admin/comment_types/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<div id="admin_comment_type_edit_form_header" data-hook>
  <h1><%= Spree.t(:editing_comment_type) %></h1>
  <%= render 'spree/shared/error_messages', :target => @comment_type %>
</div>

<div id="admin_comment_type_edit_form" data-hook>
  <%= form_for(@comment_type, :url => object_url, :html => { :method => :put }) do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>

    <div id="admin_comment_type_edit_form_buttons" data-hook>
      <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
    </div>
  <% end %>
</div>

spree_theme/app/views/spree/admin/comment_types/index.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:comment_types) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:new_comment_type), new_object_url, :icon => 'plus', :id => 'admin_new_comment_type_link' %>
  </li>
<% end %>

<table class="index" id='listing_comment_types'>
  <colgroup>
    <col style="width: 40%">
    <col style="width: 45%">
    <col style="width: 15%">
  </colgroup>
  <thead>
    <tr data-hook="admin_comment_types_index_headers">
      <th><%= Spree.t(:name) %></th>
      <th><%= Spree.t(:applies_to) %></th>
      <th data-hook="admin_comment_types_index_header_actions" class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @comment_types.each do |comment_type| %>
      <tr id="<%= dom_id comment_type %>">
      <tr id="<%= spree_dom_id comment_type %>" data-hook="admin_comment_types_index_rows" class="<%= cycle('odd', 'even')%>">
        <td><%= comment_type.name %></td>
        <td><%= comment_type.applies_to %></td>
        <td data-hook="admin_comment_types_index_row_actions" class="actions">
          <%= link_to_edit comment_type, :no_text => true %>
          <%= link_to_delete comment_type, :no_text => true  %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

spree_theme/app/views/spree/admin/comment_types/new.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:new_comment_type) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_comment_types_list), admin_comment_types_path, :icon => 'arrow-left' %>
  </li>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @comment_type } %>

<%= form_for(:comment_type, :url => collection_url) do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <div data-hook="buttons" class="filter-actions actions">
      <%= button Spree.t(:create), 'ok' %>
    </div>
  </fieldset>
<% end %>